### Create a new user
POST http://localhost:3000/auth/signup
Content-Type:  application/json

{
    "email": "ibrahimlokman.hash@gmail.com",
    "password": "dummypassword2"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type:  application/json

{
    "email": "ibrahimlokman.hash@gmail.com",
    "password": "dummypassword2"
}

### Find user by id
GET http://localhost:3000/auth/1

### Find user by email
GET http://localhost:3000/auth?email=ibrahimlokman@gmail.com

### Find all user
GET http://localhost:3000/auth

### Delete user by id
DELETE http://localhost:3000/auth/3

### Update user
PATCH http://localhost:3000/auth/2
Content-Type:  application/json

{
    "email": "ibrahimlokmanUpadated@gmail.com",
    "password": "dummypasswordUpdated"
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get a color
GET http://localhost:3000/auth/colors
